import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))


def get_llm_score(text: str) -> float:
    """
    Uses Groq (llama-3.3-70b-versatile) to estimate the probability
    that the given text was AI-generated.

    Returns a float between 0.0 (likely human) and 1.0 (likely AI).
    """
    prompt = f"""You are an expert at detecting whether text was written by a human or generated by an AI.

Analyze the following text and estimate the probability that it was AI-generated.

Consider:
- Overly uniform sentence structure and length (AI tendency)
- Generic, hedged, or formulaic phrasing (AI tendency)
- Unusual vocabulary diversity or natural irregularities (human tendency)
- Personal voice, emotional specificity, casual errors (human tendency)

Respond with ONLY a single number between 0.0 and 1.0, where:
0.0 = definitely written by a human
1.0 = definitely generated by AI

Do not include any explanation, units, or other text. Just the number.

Text to analyze:
\"\"\"
{text}
\"\"\"
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
        max_tokens=10,
    )

    raw = response.choices[0].message.content.strip()

    score = float(raw)
    return max(0.0, min(1.0, score))


if __name__ == "__main__":
    test_cases = [
        (
            "clearly AI",
            "Artificial intelligence represents a transformative paradigm shift in "
            "modern society. It is important to note that while the benefits of AI "
            "are numerous, it is equally essential to consider the ethical implications."
        ),
        (
            "clearly human",
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium in it "
            "and i was thirsty for like three hours after."
        ),
    ]

    for label, text in test_cases:
        score = get_llm_score(text)
        print(f"[{label}] llm_score = {score:.3f}")
